---
title: "Mouse_olfactory_bulb"
author:
- Joseph Bergenstråhle, Royal Institute of Technology (KTH)
- Ludvig Larsson, Royal Institute of Technology (KTH)
date: ''
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

This is a showcase of the ....


```{r}

infoTable <- read.table("~/STUtility/inst/extdata/infoTable_MOB.csv", sep=";", header=T, stringsAsFactors = F)

```

```{r}
ensids <- read.table(file = list.files(system.file("extdata", package = "STutility"), full.names = T, pattern = "mouse_genes"), header = T, sep = "\t", stringsAsFactors = F)

se <- prep.from.table(infotable = infoTable, 
                      transpose = T, 
                      min.gene.count = 100, 
                      min.gene.spots = 5,
                      min.spot.count = 500, 
                      annotation = ensids)


```

```{r}

ST.FeaturePlot(object = se, 
               features = c("nFeature_RNA", "nCount_RNA"), 
               palette = "GrRd",
               ncol = 8, 
               grid.ncol = 1, 
               pt.size = 0.5, 
               center.tissue = T)

```


```{r, eval=FALSE}

se <- LoadImages(object = se, verbose = T, time.resolve = T)
se <- MaskImages(object = se, verbose = T)
ImagePlot(se, ncols = 2)
```

```{r}

se <- AlignImages(se, verbose = T)
ImagePlot(se, ncols = 2)

```

```{r, eval=FALSE, warning=FALSE, message=FALSE} 

se <- SCTransform(se, vars.to.regress = c("sample", "nFeature_RNA"))

```

```{r, fig.width=16, fig.height=10}

se <- RunICA(se)
se <- RunUMAP(object = se, dims = 1:50, verbose = FALSE, n.components = 3, reduction = "ica", reduction.name = "umap.3d")

ST.DimPlot(object = se, dims = 1:3, reduction = "umap.3d", blend = T, dark.theme = T)

ProjectDim(se, reduction = "umap.3d")
```


```{r, fig.width=16, fig.height=10}
MultiFeatureOverlay(se, features = "Slc1a2", 
                    sampleids = paste0(1:4),
                    palette = "GrRd",
                    method = "raster")

```

```{r, fig.width=16, fig.height=10}
MultiFeatureOverlay(se, features = "Kctd12", 
                    sampleids = paste0(1:4),
                    palette = "GrRd",
                    method = "raster")

```

```{r, fig.width=16, fig.height=10}
MultiFeatureOverlay(se, features = "Nefl", 
                    sampleids = paste0(1:4),
                    palette = "GrRd",
                    method = "raster")

```

Om man vill ha de längst in tex:


```{r, fig.width=16, fig.height=10}
#spara gg ploten
gg<-ST.DimPlot(object = se, dims = 1:3, reduction = "umap.3d", blend = T, dark.theme = T)
#kor plotly
ST.rgbDimPlot(plot = gg)
#notera fargerna
#Red > 50
#Green < 20
#blue >35 <50

se <- labelRGB(object = se, dimPlot = gg, 
                label1="inner", red1=c(50,255), green1=c(0,20), blue1=c(35,50)
                )

de.markers <- FindMarkers(se, ident.1 = "inner")

head(de.markers)
```

```{r, fig.width=16, fig.height=10}
MultiFeatureOverlay(se, features = "Nrgn", 
                    sampleids = paste0(1:4),
                    palette = "GrRd",
                    method = "raster")

MultiFeatureOverlay(se, features = "Penk", 
                    sampleids = paste0(1:4),
                    palette = "GrRd",
                    method = "raster")
ST.FeaturePlot(object=se,
               features=c("Nrgn","Penk", "Ppp3ca", "Tshz1"),
               palette = "GrRd",
               pt.size = 1,
               dark.theme = T)
```


```{r, fig.width=16, fig.height=10}

df <- as.data.frame(se@reductions$umap.3d@cell.embeddings)

gg <- ggplot(df, aes(x=UMAP_1, y=UMAP_2, col=UMAP_3))+geom_point()
plot_gg(gg,multicore=TRUE,width=5,height=5,scale=250)
```




